<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<NoWarn>$(NoWarn);NU1902;NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SSO.Domain.Management\SSO.Domain.Management.csproj" />
    <ProjectReference Include="..\SSO.Domain\SSO.Domain.csproj" />
    <ProjectReference Include="..\SSO.Infrastructure\SSO.Infrastructure.csproj" />
  </ItemGroup>

</Project>
